# FROM hashicorp/terraform:1.0.10
FROM node:alpine

# RUN apk update && apk add nodejs
# RUN apk update && apk add npm
RUN npm install -g firebase-tools
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
# RUN npm install --global yarn
RUN apk add docker docker-compose

WORKDIR /app
RUN 
COPY . .
RUN npm install

CMD ["npm", "start"]